// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaKPI_API.Context;

namespace SistemaKPI_API.Migrations
{
    [DbContext(typeof(SistemaKPIContext))]
    [Migration("20190416221153_MigracionNuevasEntidadesPedidoCliente4")]
    partial class MigracionNuevasEntidadesPedidoCliente4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaKPI_API.Entities.Cliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RazonSocial");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.InventarioFisico", b =>
                {
                    b.Property<Guid>("IdInventarioFisico")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoProducto");

                    b.Property<DateTime>("FechaInventario");

                    b.Property<string>("FolioRemision");

                    b.Property<string>("NombreProducto");

                    b.Property<string>("NumBolsas");

                    b.HasKey("IdInventarioFisico");

                    b.ToTable("InventarioFisico");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.MovimientosAlmacen2", b =>
                {
                    b.Property<Guid>("IdMovimientoAlmacen")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoProducto");

                    b.Property<DateTime>("FechaMovimiento");

                    b.Property<string>("FolioRemision");

                    b.Property<string>("NombreProducto");

                    b.Property<string>("NumBolsas");

                    b.Property<string>("TipoMovimiento");

                    b.Property<string>("Turno");

                    b.HasKey("IdMovimientoAlmacen");

                    b.ToTable("MovimientosAlmacen");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.PedidoDiario", b =>
                {
                    b.Property<Guid>("IdPedidoDiario")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdProducto");

                    b.Property<int>("NumBolsas");

                    b.Property<int>("NumDia");

                    b.Property<Guid?>("PedidoSemanalIdPedidoSemanal");

                    b.HasKey("IdPedidoDiario");

                    b.HasIndex("IdProducto");

                    b.HasIndex("PedidoSemanalIdPedidoSemanal");

                    b.ToTable("PedidoDiario");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.PedidoSemanal", b =>
                {
                    b.Property<Guid>("IdPedidoSemanal")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaFinSemana");

                    b.Property<DateTime>("FechaInicioSemana");

                    b.HasKey("IdPedidoSemanal");

                    b.ToTable("PedidoSemanal");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodigoProducto");

                    b.Property<Guid?>("IdCliente1");

                    b.Property<string>("NombreProducto");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCliente1");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.ReporteDiarioPedidosClienteCSV", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anho");

                    b.Property<string>("Capacidad");

                    b.Property<string>("Cargadores");

                    b.Property<string>("Cliente");

                    b.Property<string>("CodigoCargadores");

                    b.Property<string>("CodigoChofer");

                    b.Property<string>("CodigoNuevo");

                    b.Property<string>("DiaDeSemana");

                    b.Property<string>("DiaDelMes");

                    b.Property<string>("Flete");

                    b.Property<string>("NombreDelChofer");

                    b.Property<string>("NombreMes");

                    b.Property<string>("NumBolzXTarima");

                    b.Property<string>("NumDeDia");

                    b.Property<string>("NumPzBol");

                    b.Property<string>("NumPzXTarima");

                    b.Property<string>("NumeroDeCaja");

                    b.Property<string>("PedidoPorBolsa");

                    b.Property<string>("PedidoPorPieza");

                    b.Property<string>("PorcentajeCumplimiento");

                    b.Property<string>("Presentacion");

                    b.Property<string>("SemanaAnual");

                    b.Property<string>("SemanaMes");

                    b.Property<string>("SurtidoPorBolsa");

                    b.Property<string>("SurtidoPorPz");

                    b.Property<string>("TiempoDeCarga");

                    b.HasKey("IdPedido");

                    b.ToTable("ReporteDiarioPedidosClienteCSV");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.ReporteProduccion", b =>
                {
                    b.Property<Guid>("IdProduccion")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anho");

                    b.Property<string>("CantidadBolsas");

                    b.Property<string>("CantidadPiezas");

                    b.Property<string>("Capacidad");

                    b.Property<string>("Cliente");

                    b.Property<string>("CodigoNuevo");

                    b.Property<string>("Dia");

                    b.Property<string>("Eficiencia");

                    b.Property<string>("Familia");

                    b.Property<string>("HRUsadas");

                    b.Property<string>("Maquina");

                    b.Property<string>("Mes");

                    b.Property<string>("MinutosUsados");

                    b.Property<string>("Poletileno");

                    b.Property<string>("Presentacion");

                    b.Property<string>("ScrapBolsa");

                    b.Property<string>("ScrapPolietilenoGr");

                    b.Property<string>("Semana");

                    b.Property<string>("Supervisor");

                    b.Property<string>("TiempoDecimal");

                    b.Property<string>("TotalDeCavidades");

                    b.Property<string>("Turno");

                    b.HasKey("IdProduccion");

                    b.ToTable("ReporteProduccion");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.PedidoDiario", b =>
                {
                    b.HasOne("SistemaKPI_API.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto");

                    b.HasOne("SistemaKPI_API.Entities.PedidoSemanal")
                        .WithMany("IdPedidoDiario")
                        .HasForeignKey("PedidoSemanalIdPedidoSemanal");
                });

            modelBuilder.Entity("SistemaKPI_API.Entities.Producto", b =>
                {
                    b.HasOne("SistemaKPI_API.Entities.Cliente", "IdCliente")
                        .WithMany()
                        .HasForeignKey("IdCliente1");
                });
#pragma warning restore 612, 618
        }
    }
}
